version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directories:
      - /demo/preview-h5
      - /website
      - /scripts/checks
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
